spring.application.name=publicservice

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

server.servlet.jsp.init-parameters.development=true
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/publicservice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1111

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true